#!/bin/bash

# Make sure the user data directory is owned by the developer user
if [ -d /home/developer/.netbeans ]; then
  sudo chown developer:developer /home/developer/.netbeans
fi
exec /usr/local/netbeans-8.1/bin/netbeans --jdkhome /usr/lib/jvm/jdk1.8.0_91/
